<<<<<<< HEAD
# Generated by Django 4.2.20 on 2025-04-04 11:47
=======
# Generated by Django 4.2.20 on 2025-04-04 09:11
>>>>>>> 792bac74aa14b27adb356dea1d4d55a8a3318ddd

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0003_alter_follow_following_alter_follow_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
<<<<<<< HEAD
            options={'ordering': ('-pub_date',)},
=======
            options={'ordering': ('pub_date',)},
>>>>>>> 792bac74aa14b27adb356dea1d4d55a8a3318ddd
        ),
        migrations.AlterField(
            model_name='follow',
            name='following',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='follow',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='following', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='follow',
<<<<<<< HEAD
            constraint=models.UniqueConstraint(fields=('user', 'following'), name='unique_follower'),
        ),
        migrations.AddConstraint(
            model_name='follow',
            constraint=models.CheckConstraint(check=models.Q(('user', models.F('following')), _negated=True), name='self_following'),
=======
            constraint=models.UniqueConstraint(fields=('user', 'following'), name='unique_follower', violation_error_message='Подписка уже существует!'),
        ),
        migrations.AddConstraint(
            model_name='follow',
            constraint=models.CheckConstraint(check=models.Q(('user', models.F('following')), _negated=True), name='self-following', violation_error_message='Нельзя подписаться на себя!'),
>>>>>>> 792bac74aa14b27adb356dea1d4d55a8a3318ddd
        ),
    ]
